class GeoHelper {
    /**
     * Try getting the City+State for a given city
     */
    public tryGetFullCity(city: string): string {
        let zipCode = parseInt(city);
        if (!isNaN(zipCode)) {
            // zip code - all good
            return city;
        }

        let match = this._knownTopUSCities[(city || '').trim().toLowerCase()];
        if (match) {
            return `${match.city}, ${match.state}`;
        } else {
            return city;
        }
    }

    /**
     * Known city to city+state mapping for top 300 US cities
     */
    private _knownTopUSCities: any = {
        'new york': { city: 'New York', state: 'NY' },
        'los angeles': { city: 'Los Angeles', state: 'CA' },
        'chicago': { city: 'Chicago', state: 'IL' },
        'houston': { city: 'Houston', state: 'TX' },
        'philadelphia': { city: 'Philadelphia', state: 'PA' },
        'phoenix': { city: 'Phoenix', state: 'AZ' },
        'san diego': { city: 'San Diego', state: 'CA' },
        'dallas': { city: 'Dallas', state: 'TX' },
        'san antonio': { city: 'San Antonio', state: 'TX' },
        'detroit': { city: 'Detroit', state: 'MI' },
        'san jose': { city: 'San Jose', state: 'CA' },
        'indianapolis': { city: 'Indianapolis', state: 'IN' },
        'san francisco': { city: 'San Francisco', state: 'CA' },
        'jacksonville': { city: 'Jacksonville', state: 'FL' },
        'columbus': { city: 'Columbus', state: 'OH' },
        'austin': { city: 'Austin', state: 'TX' },
        'memphis': { city: 'Memphis', state: 'TN' },
        'baltimore': { city: 'Baltimore', state: 'MD' },
        'milwaukee': { city: 'Milwaukee', state: 'WI' },
        'boston': { city: 'Boston', state: 'MA' },
        'charlotte': { city: 'Charlotte', state: 'NC' },
        'el paso': { city: 'El Paso', state: 'TX' },
        'washington': { city: 'Washington', state: 'DE' },
        'nashville-davidson': { city: 'Nashville-Davidson', state: 'TN' },
        'seattle': { city: 'Seattle', state: 'WA' },
        'fort worth': { city: 'Fort Worth', state: 'TX' },
        'denver': { city: 'Denver', state: 'CO' },
        'portland': { city: 'Portland', state: 'OR' },
        'oklahoma': { city: 'Oklahoma', state: 'OK' },
        'las vegas': { city: 'Las Vegas', state: 'NV' },
        'tucson': { city: 'Tucson', state: 'AZ' },
        'new orleans': { city: 'New Orleans', state: 'LA' },
        'long beach': { city: 'Long Beach', state: 'CA' },
        'cleveland': { city: 'Cleveland', state: 'OH' },
        'albuquerque': { city: 'Albuquerque', state: 'NM' },
        'fresno': { city: 'Fresno', state: 'CA' },
        'kansas': { city: 'Kansas', state: 'MO' },
        'sacramento': { city: 'Sacramento', state: 'CA' },
        'virginia beach': { city: 'Virginia Beach', state: 'VA' },
        'mesa': { city: 'Mesa', state: 'AZ' },
        'atlanta': { city: 'Atlanta', state: 'GA' },
        'oakland': { city: 'Oakland', state: 'CA' },
        'omaha': { city: 'Omaha', state: 'NE' },
        'tulsa': { city: 'Tulsa', state: 'OK' },
        'honolulu cdp': { city: 'Honolulu CDP', state: 'HI' },
        'minneapolis': { city: 'Minneapolis', state: 'MN' },
        'miami': { city: 'Miami', state: 'FL' },
        'colorado springs': { city: 'Colorado Springs', state: 'CO' },
        'wichita': { city: 'Wichita', state: 'KS' },
        'arlington': { city: 'Arlington', state: 'TX' },
        'santa ana': { city: 'Santa Ana', state: 'CA' },
        'st. louis': { city: 'St. Louis', state: 'MO' },
        'anaheim': { city: 'Anaheim', state: 'CA' },
        'pittsburgh': { city: 'Pittsburgh', state: 'PA' },
        'cincinnati': { city: 'Cincinnati', state: 'OH' },
        'tampa': { city: 'Tampa', state: 'FL' },
        'toledo': { city: 'Toledo', state: 'OH' },
        'raleigh': { city: 'Raleigh', state: 'NC' },
        'buffalo': { city: 'Buffalo', state: 'NY' },
        'aurora': { city: 'Aurora', state: 'CO' },
        'st. paul': { city: 'St. Paul', state: 'MN' },
        'corpus christi': { city: 'Corpus Christi', state: 'TX' },
        'newark': { city: 'Newark', state: 'NJ' },
        'riverside': { city: 'Riverside', state: 'CA' },
        'anchorage': { city: 'Anchorage', state: 'AK' },
        'lexington-fayette': { city: 'Lexington-Fayette', state: 'KY' },
        'stockton': { city: 'Stockton', state: 'CA' },
        'bakersfield': { city: 'Bakersfield', state: 'CA' },
        'louisville': { city: 'Louisville', state: 'KY' },
        'st. petersburg': { city: 'St. Petersburg', state: 'FL' },
        'jersey': { city: 'Jersey', state: 'NJ' },
        'birmingham': { city: 'Birmingham', state: 'AL' },
        'norfolk': { city: 'Norfolk', state: 'VA' },
        'plano': { city: 'Plano', state: 'TX' },
        'lincoln': { city: 'Lincoln', state: 'NE' },
        'glendale': { city: 'Glendale', state: 'AZ' },
        'greensboro': { city: 'Greensboro', state: 'NC' },
        'hialeah': { city: 'Hialeah', state: 'FL' },
        'baton rouge': { city: 'Baton Rouge', state: 'LA' },
        'garland': { city: 'Garland', state: 'TX' },
        'rochester': { city: 'Rochester', state: 'NY' },
        'scottsdale': { city: 'Scottsdale', state: 'AZ' },
        'madison': { city: 'Madison', state: 'WI' },
        'akron': { city: 'Akron', state: 'OH' },
        'fort wayne': { city: 'Fort Wayne', state: 'IN' },
        'fremont': { city: 'Fremont', state: 'CA' },
        'chesapeake': { city: 'Chesapeake', state: 'VA' },
        'henderson': { city: 'Henderson', state: 'NV' },
        'lubbock': { city: 'Lubbock', state: 'TX' },
        'modesto': { city: 'Modesto', state: 'CA' },
        'chandler': { city: 'Chandler', state: 'AZ' },
        'montgomery': { city: 'Montgomery', state: 'AL' },
        //'glendale': {city: 'Glendale', state: 'CA'},
        'shreveport': { city: 'Shreveport', state: 'LA' },
        'des moines': { city: 'Des Moines', state: 'IA' },
        'augusta-richmond': { city: 'Augusta-Richmond', state: 'GA' },
        'tacoma': { city: 'Tacoma', state: 'WA' },
        'richmond': { city: 'Richmond', state: 'VA' },
        'yonkers': { city: 'Yonkers', state: 'NY' },
        'grand rapids': { city: 'Grand Rapids', state: 'MI' },
        'spokane': { city: 'Spokane', state: 'WA' },
        'irving': { city: 'Irving', state: 'TX' },
        'durham': { city: 'Durham', state: 'NC' },
        'mobile': { city: 'Mobile', state: 'AL' },
        'chula vista': { city: 'Chula Vista', state: 'CA' },
        'huntington beach': { city: 'Huntington Beach', state: 'CA' },
        'orlando': { city: 'Orlando', state: 'FL' },
        'san bernardino': { city: 'San Bernardino', state: 'CA' },
        'laredo': { city: 'Laredo', state: 'TX' },
        'reno': { city: 'Reno', state: 'NV' },
        'arlington cdp': { city: 'Arlington CDP', state: 'VA' },
        'boise': { city: 'Boise', state: 'ID' },
        'winston-salem': { city: 'Winston-Salem', state: 'NC' },
        //'columbus': {city: 'Columbus', state: 'GA'},
        'little rock': { city: 'Little Rock', state: 'AR' },
        'salt lake': { city: 'Salt Lake', state: 'UT' },
        'jackson': { city: 'Jackson', state: 'MS' },
        'newport news': { city: 'Newport News', state: 'VA' },
        'oxnard': { city: 'Oxnard', state: 'CA' },
        'amarillo': { city: 'Amarillo', state: 'TX' },
        'providence': { city: 'Providence', state: 'RI' },
        'worcester': { city: 'Worcester', state: 'MA' },
        'knoxville': { city: 'Knoxville', state: 'TN' },
        'garden grove': { city: 'Garden Grove', state: 'CA' },
        'oceanside': { city: 'Oceanside', state: 'CA' },
        'ontario': { city: 'Ontario', state: 'CA' },
        'dayton': { city: 'Dayton', state: 'OH' },
        'huntsville': { city: 'Huntsville', state: 'AL' },
        'irvine': { city: 'Irvine', state: 'CA' },
        'santa clarita': { city: 'Santa Clarita', state: 'CA' },
        'tempe': { city: 'Tempe', state: 'AZ' },
        'overland park': { city: 'Overland Park', state: 'KS' },
        'fort lauderdale': { city: 'Fort Lauderdale', state: 'FL' },
        //'aurora': {city: 'Aurora', state: 'IL'},
        'chattanooga': { city: 'Chattanooga', state: 'TN' },
        'tallahassee': { city: 'Tallahassee', state: 'FL' },
        'pomona': { city: 'Pomona', state: 'CA' },
        'santa rosa': { city: 'Santa Rosa', state: 'CA' },
        //'springfield': {city: 'Springfield', state: 'MA'},
        'rockford': { city: 'Rockford', state: 'IL' },
        //'springfield': {city: 'Springfield', state: 'MO'},
        'moreno valley': { city: 'Moreno Valley', state: 'CA' },
        'paterson': { city: 'Paterson', state: 'NJ' },
        'brownsville': { city: 'Brownsville', state: 'TX' },
        'vancouver': { city: 'Vancouver', state: 'WA' },
        'salinas': { city: 'Salinas', state: 'CA' },
        //'kansas': {city: 'Kansas', state: 'KS'},
        'pembroke pines': { city: 'Pembroke Pines', state: 'FL' },
        'hampton': { city: 'Hampton', state: 'VA' },
        'syracuse': { city: 'Syracuse', state: 'NY' },
        'pasadena': { city: 'Pasadena', state: 'TX' },
        'lakewood': { city: 'Lakewood', state: 'CO' },
        'rancho cucamonga': { city: 'Rancho Cucamonga', state: 'CA' },
        'fontana': { city: 'Fontana', state: 'CA' },
        'hollywood': { city: 'Hollywood', state: 'FL' },
        'hayward': { city: 'Hayward', state: 'CA' },
        'torrance': { city: 'Torrance', state: 'CA' },
        'salem': { city: 'Salem', state: 'OR' },
        'eugene': { city: 'Eugene', state: 'OR' },
        'bridgeport': { city: 'Bridgeport', state: 'CT' },
        //'pasadena': {city: 'Pasadena', state: 'CA'},
        'corona': { city: 'Corona', state: 'CA' },
        'warren': { city: 'Warren', state: 'MI' },
        'escondido': { city: 'Escondido', state: 'CA' },
        'north las vegas': { city: 'North Las Vegas', state: 'NV' },
        'naperville': { city: 'Naperville', state: 'IL' },
        'grand prairie': { city: 'Grand Prairie', state: 'TX' },
        'gilbert town': { city: 'Gilbert town', state: 'AZ' },
        'orange': { city: 'Orange', state: 'CA' },
        'alexandria': { city: 'Alexandria', state: 'VA' },
        'sioux falls': { city: 'Sioux Falls', state: 'SD' },
        'sunnyvale': { city: 'Sunnyvale', state: 'CA' },
        'fullerton': { city: 'Fullerton', state: 'CA' },
        'mesquite': { city: 'Mesquite', state: 'TX' },
        'savannah': { city: 'Savannah', state: 'GA' },
        'sterling heights': { city: 'Sterling Heights', state: 'MI' },
        'coral springs': { city: 'Coral Springs', state: 'FL' },
        'concord': { city: 'Concord', state: 'CA' },
        'fort collins': { city: 'Fort Collins', state: 'CO' },
        'lancaster': { city: 'Lancaster', state: 'CA' },
        'hartford': { city: 'Hartford', state: 'CT' },
        'palmdale': { city: 'Palmdale', state: 'CA' },
        'fayetteville': { city: 'Fayetteville', state: 'NC' },
        'new haven': { city: 'New Haven', state: 'CT' },
        'elizabeth': { city: 'Elizabeth', state: 'NJ' },
        'peoria': { city: 'Peoria', state: 'AZ' },
        'thousand oaks': { city: 'Thousand Oaks', state: 'CA' },
        'cedar rapids': { city: 'Cedar Rapids', state: 'IA' },
        'topeka': { city: 'Topeka', state: 'KS' },
        'flint': { city: 'Flint', state: 'MI' },
        'el monte': { city: 'El Monte', state: 'CA' },
        'stamford': { city: 'Stamford', state: 'CT' },
        'vallejo': { city: 'Vallejo', state: 'CA' },
        'evansville': { city: 'Evansville', state: 'IN' },
        'lansing': { city: 'Lansing', state: 'MI' },
        'joliet': { city: 'Joliet', state: 'IL' },
        'columbia': { city: 'Columbia', state: 'SC' },
        'simi valley': { city: 'Simi Valley', state: 'CA' },
        'waco': { city: 'Waco', state: 'TX' },
        'abilene': { city: 'Abilene', state: 'TX' },
        'ann arbor': { city: 'Ann Arbor', state: 'MI' },
        'carrollton': { city: 'Carrollton', state: 'TX' },
        'inglewood': { city: 'Inglewood', state: 'CA' },
        'mcallen': { city: 'McAllen', state: 'TX' },
        'independence': { city: 'Independence', state: 'MO' },
        'cape coral': { city: 'Cape Coral', state: 'FL' },
        'bellevue': { city: 'Bellevue', state: 'WA' },
        'beaumont': { city: 'Beaumont', state: 'TX' },
        //'peoria': {city: 'Peoria', state: 'IL'},
        //'springfield': {city: 'Springfield', state: 'IL'},
        'lafayette': { city: 'Lafayette', state: 'LA' },
        'west valley': { city: 'West Valley', state: 'UT' },
        'costa mesa': { city: 'Costa Mesa', state: 'CA' },
        'downey': { city: 'Downey', state: 'CA' },
        'manchester': { city: 'Manchester', state: 'NH' },
        'clearwater': { city: 'Clearwater', state: 'FL' },
        'waterbury': { city: 'Waterbury', state: 'CT' },
        'west covina': { city: 'West Covina', state: 'CA' },
        'south bend': { city: 'South Bend', state: 'IN' },
        'allentown': { city: 'Allentown', state: 'PA' },
        'norwalk': { city: 'Norwalk', state: 'CA' },
        'clarksville': { city: 'Clarksville', state: 'TN' },
        'provo': { city: 'Provo', state: 'UT' },
        'lowell': { city: 'Lowell', state: 'MA' },
        'athens-clarke county': { city: 'Athens-Clarke County', state: 'GA' },
        'berkeley': { city: 'Berkeley', state: 'CA' },
        'ventura': { city: 'Ventura', state: 'CA' },
        'westminster': { city: 'Westminster', state: 'CO' },
        'pueblo': { city: 'Pueblo', state: 'CO' },
        'wichita falls': { city: 'Wichita Falls', state: 'TX' },
        'burbank': { city: 'Burbank', state: 'CA' },
        //'richmond': {city: 'Richmond', state: 'CA'},
        'arvada': { city: 'Arvada', state: 'CO' },
        'erie': { city: 'Erie', state: 'PA' },
        'fairfield': { city: 'Fairfield', state: 'CA' },
        'daly': { city: 'Daly', state: 'CA' },
        'santa clara': { city: 'Santa Clara', state: 'CA' },
        'cambridge': { city: 'Cambridge', state: 'MA' },
        'green bay': { city: 'Green Bay', state: 'WI' },
        'olathe': { city: 'Olathe', state: 'KS' },
        'gary': { city: 'Gary', state: 'IN' },
        'livonia': { city: 'Livonia', state: 'MI' },
        'antioch': { city: 'Antioch', state: 'CA' },
        'portsmouth': { city: 'Portsmouth', state: 'VA' },
        'centennial': { city: 'Centennial', state: 'CO' },
        'charleston': { city: 'Charleston', state: 'SC' },
        'south gate': { city: 'South Gate', state: 'CA' },
        'port st. lucie': { city: 'Port St. Lucie', state: 'FL' },
        'cary town': { city: 'Cary town', state: 'NC' },
        'dearborn': { city: 'Dearborn', state: 'MI' },
        'norman': { city: 'Norman', state: 'OK' },
        'davenport': { city: 'Davenport', state: 'IA' },
        'everett': { city: 'Everett', state: 'WA' },
        'richardson': { city: 'Richardson', state: 'TX' },
        'visalia': { city: 'Visalia', state: 'CA' },
        'rialto': { city: 'Rialto', state: 'CA' },
        'elgin': { city: 'Elgin', state: 'IL' },
        'mission viejo': { city: 'Mission Viejo', state: 'CA' },
        'macon': { city: 'Macon', state: 'GA' },
        'midland': { city: 'Midland', state: 'TX' },
        'compton': { city: 'Compton', state: 'CA' },
        'el cajon': { city: 'El Cajon', state: 'CA' },
        'brockton': { city: 'Brockton', state: 'MA' },
        'gainesville': { city: 'Gainesville', state: 'FL' },
        'gresham': { city: 'Gresham', state: 'OR' },
        'boulder': { city: 'Boulder', state: 'CO' },
        'new bedford': { city: 'New Bedford', state: 'MA' },
        'roanoke': { city: 'Roanoke', state: 'VA' },
        'albany': { city: 'Albany', state: 'NY' },
        'thornton': { city: 'Thornton', state: 'CO' },
        'vacaville': { city: 'Vacaville', state: 'CA' },
        'carson': { city: 'Carson', state: 'CA' },
        'killeen': { city: 'Killeen', state: 'TX' },
        'fall river': { city: 'Fall River', state: 'MA' },
        'kenosha': { city: 'Kenosha', state: 'WI' },
        'billings': { city: 'Billings', state: 'MT' },
        'san mateo': { city: 'San Mateo', state: 'CA' },
        'roseville': { city: 'Roseville', state: 'CA' },
        'vista': { city: 'Vista', state: 'CA' },
        'lawton': { city: 'Lawton', state: 'OK' },
        'waukegan': { city: 'Waukegan', state: 'IL' },
        'fargo': { city: 'Fargo', state: 'ND' },
        'odessa': { city: 'Odessa', state: 'TX' },
        'wilmington': { city: 'Wilmington', state: 'NC' },
        'high point': { city: 'High Point', state: 'NC' },
        //'rochester': {city: 'Rochester', state: 'MN'},
        'miramar': { city: 'Miramar', state: 'FL' },
        'denton': { city: 'Denton', state: 'TX' },
        'lynn': { city: 'Lynn', state: 'MA' },
        'miami beach': { city: 'Miami Beach', state: 'FL' },
        //'westminster': {city: 'Westminster', state: 'CA'},
        'santa barbara': { city: 'Santa Barbara', state: 'CA' },
        'sandy': { city: 'Sandy', state: 'UT' },
        'quincy': { city: 'Quincy', state: 'MA' },
        'citrus heights': { city: 'Citrus Heights', state: 'CA' },
        'sunrise': { city: 'Sunrise', state: 'FL' },
        'nashua': { city: 'Nashua', state: 'NH' },
        'alhambra': { city: 'Alhambra', state: 'CA' },
        'san angelo': { city: 'San Angelo', state: 'TX' },
        'pompano beach': { city: 'Pompano Beach', state: 'FL' },
    };
};

export = new GeoHelper;